include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - module/ui/lib/extension/logger.dart
  errors:
    unused_field: ignore
    avoid_empty_else: error
    no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
    only_throw_errors: ignore
    unused_element: ignore
    unnecessary_parenthesis: ignore
    library_names: ignore
    unnecessary_string_escapes: ignore
    constant_identifier_names: ignore
    unnecessary_library_name: ignore
    dangling_library_doc_comments: ignore
    always_put_control_body_on_new_line: ignore
    use_super_parameters: ignore
    prefer_int_literals: ignore
    strict_top_level_inference: ignore
    unnecessary_overrides: ignore
    avoid_function_literals_in_foreach_calls: ignore
    deprecated_member_use: ignore
    unnecessary_string_interpolations: ignore
    sort_pub_dependencies: ignore
    depend_on_referenced_packages: ignore
    annotate_overrides: ignore
    prefer_initializing_formals: ignore
    library_private_types_in_public_api: ignore
    avoid_print: ignore
    use_key_in_widget_constructors: ignore
    sort_child_properties_last: ignore
    unnecessary_this: ignore
    unnecessary_new: ignore
    prefer_collection_literals: ignore
    unintended_html_in_doc_comment: ignore
    unused_catch_stack: ignore
    override_on_non_overriding_member: ignore
    no_default_cases: ignore
    provide_deprecation_message: ignore
    no_leading_underscores_for_library_prefixes: ignore
    prefer_typing_uninitialized_variables: ignore
    always_declare_return_types: ignore
    curly_braces_in_flow_control_structures: ignore
    prefer_null_aware_method_calls: ignore
    unnecessary_brace_in_string_interps: ignore
    prefer_is_not_operator: ignore
    avoid_types_as_parameter_names: ignore
    use_function_type_syntax_for_parameters: ignore
    undefined_hidden_name: ignore
    use_named_constants: ignore

linter:
  rules:
    # prefer_relative_imports is disabled for generated files that use absolute imports
    - avoid_empty_else
    - avoid_print
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_escaping_inner_quotes
    - avoid_final_parameters
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - camel_case_extensions
    - await_only_futures
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - non_constant_identifier_names
    - noop_primitive_operations
    - only_throw_errors
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_final_fields
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - recursive_getters
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_named_constants
    - use_rethrow_when_possible
    - use_string_buffers
    - use_to_and_as_if_applicable
    - package_names
    - secure_pubspec_urls
    - sort_pub_dependencies
