targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/**
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern:
            "Impl$|Helper$|DataSource$|Repository$|UseCase$|Bloc$|Controller$|Manager$"
          file_name_pattern:
            "_impl$|_helper$|_data_source$|_repository$|_use_case$|_bloc$|_controller$|_manager$"