name: cc_mixin
description: Reusable mixins for the project.
version: 1.0.0
publish_to: none
repository: https://github.com/huytower/cc_core_sdk
homepage: https://github.com/huytower/cc_core_sdk

environment:
  sdk: '^3.12.0'

resolution: workspace

dependencies:
  cc_sdk:
    path: ../cc_sdk
  cc_sdk_data:
    path: ../cc_sdk_data
  cc_sdk_ui:
    path: ../cc_sdk_ui
  flutter:
    sdk: flutter
  get: ^4.7.3
  loadmore: ^2.1.0
  multiple_result: ^5.3.0
  custom_refresh_indicator: ^4.0.1
  lottie: ^3.3.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.15.0
