name: theme
description: A Flutter theme module providing consistent theming and styling across the application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.11.5'
  flutter: '>=3.41.9'

resolution: workspace

dependencies:
  # Internal dependencies
  cc_sdk:
    path: ../../cc_core_sdk/cc_sdk
  cc_sdk_ui:
    path: ../../cc_core_sdk/cc_sdk_ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.1.0
  message:
    path: ../message

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this package as a plugin project.
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/lottie/
  #    - packages/theme/assets/background/

  # Fonts and other font-related configurations
  fonts: [ ]  # Empty list as we're using google_fonts package
  # Example font configuration (uncomment and modify as needed)
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

  # Enable generation of localized strings
  generate: true

  # Add any additional Flutter configurations here
  # For example, to enable Material 3 theming:
  # uses-material-design: true
  # material-design-3: true
