name: message
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '^3.11.5'
  flutter: '>=3.41.9'

resolution: workspace

dependencies:

  easy_localization: ^3.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lean_builder: ^0.1.10

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
