targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/**
          exclude:
            - lib/core/navigation/**
        options:
          auto_register: true
          class_name_pattern:
            "Impl$|DataSource$|Repository$|UseCase$|Bloc$"
          file_name_pattern:
            "_impl$|_data_source$|_repository$|_use_case$|_bloc$"
      injectable_generator:injectable_config_builder:
        generate_for:
          include:
            - lib/**
          exclude:
            - lib/core/navigation/**
